# Generated by Django 3.0 on 2019-12-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20191222_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national', models.CharField(max_length=50)),
                ('limit', models.CharField(max_length=50)),
            ],
        ),
    ]
